/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package u0.movieratings.scottgriffin;
import java.io.IOException;
import java.util.*;


public class App {
    public static void main(String[] args) throws IOException {
        RatingReader ratingReader = new RatingReader("movie-ratings.csv");
        List<Rating> ratingsList = ratingReader.getAllRatings();

        //   M O V I E   A V E R A G E   R A T I N G   C A L L S   (phase 5)
        Map<String, Double> movieAvgRatingMap = averageRating(ratingsList);
        printMovieAvgRatingMap(movieAvgRatingMap);

        //   H I G H E S T  /  L O W E S T   R A T E R S   F O R  E A C H   M O V I E   C A L L S    
        Map<String, List<Rating>> highestRaterMap = highestRater(ratingsList);   //phase 6
        Map<String, List<Rating>> lowestRaterMap = lowestRater(ratingsList);     //challenge 2
        printHighLowRatersMaps(highestRaterMap, true);    // used the same method for high/low prints, not sure if that is best solution..
        printHighLowRatersMaps(lowestRaterMap, false);

        //   H I G H E S T  /  L O W E S T   1 0   R A T E R   C A L L S   
        Map<String, Double> raterAverageMap = raterAverage(ratingsList);     //phase 7
        printHighestOrLowestRaters(raterAverageMap, true);                   //challenge 1
        printHighestOrLowestRaters(raterAverageMap, false);                  //challenge 1

    }  //  ======================   E N D   O F   M A I N   ====================== 




    //  A V E R A G E   R A T I N G
    public static Map<String, Double> averageRating(List<Rating> ratingsList){
        Map<String, List<Integer>> allRatingsMap = new HashMap<String, List<Integer>>();
        Map<String, Double> movieAvgRatingMap = new HashMap<>();

        //Populate allRatingsMap with list
        for (Rating r :ratingsList){
            String movieName = r.getMovieName();
            if (!allRatingsMap.containsKey(movieName)) {
                allRatingsMap.put(movieName, new ArrayList<Integer>());
            }
            allRatingsMap.get(movieName).add(r.getMovieRating());
        }

        //Calculate Averages and populate movieAverageMap
        for(String title : allRatingsMap.keySet()){
            int numOfRatings = allRatingsMap.get(title).size();
            Double totalRating = 0.0;
            for (int i : allRatingsMap.get(title)){
                totalRating += i;
            }
            double avgRating = totalRating / numOfRatings;
            movieAvgRatingMap.put(title, avgRating);
        }

        return movieAvgRatingMap;
    }

    //  P R I N T   M O V I E   A V E R A G E   M A P 
    public static void printMovieAvgRatingMap(Map<String, Double> movieAvgRatingMap){
        System.out.println("");
        System.out.println(" - - - - -   M O V I E   A V E R A G E   R A T I N G   - - - - - ");
        System.out.println("");

        for(String movieName : movieAvgRatingMap.keySet()){
            System.out.println("Movie Name     : " + movieName);
            System.out.println("Average Rating : " + movieAvgRatingMap.get(movieName));
            System.out.println(""); 
        }


               
        
    }
    
    //  H I G H E S T   R A T E R    
    public static Map<String, List<Rating>> highestRater(List<Rating> ratingsList){
        Map<String, List<Rating>> highestRaterMap = new HashMap<>();

        //populate map
        for(Rating r : ratingsList){
            String movieName = r.getMovieName();   
            int movieRating = r.getMovieRating();
        
            if(!highestRaterMap.containsKey(movieName)){
                highestRaterMap.put(movieName, new ArrayList<Rating>());
                highestRaterMap.get(movieName).add(r);
            }
            else {
                int currentHigh = highestRaterMap.get(movieName).get(0).getMovieRating();

                //clear if new high
                if (movieRating > currentHigh){
                    highestRaterMap.get(movieName).clear();
                }
                //set if new high or equal high
                if (movieRating >= currentHigh){
                    highestRaterMap.get(movieName).add(r);
                }
                //do nothing if rating less than current high
            }
        }
        return highestRaterMap;
    } 
    
    //  L O W E S T   R A T E R    
    public static Map<String, List<Rating>> lowestRater(List<Rating> ratingsList){
        Map<String, List<Rating>> lowestRaterMap = new HashMap<>();

        //populate map
        for(Rating r : ratingsList){
            String movieName = r.getMovieName();   
            int movieRating = r.getMovieRating();
        
            if(!lowestRaterMap.containsKey(movieName)){
                lowestRaterMap.put(movieName, new ArrayList<Rating>());
                lowestRaterMap.get(movieName).add(r);
            }
            else {
                int currentLow = lowestRaterMap.get(movieName).get(0).getMovieRating();

                //clear if new low
                if (movieRating < currentLow){
                    lowestRaterMap.get(movieName).clear();
                }
                //set if new low or equal high
                if (movieRating <= currentLow){
                    lowestRaterMap.get(movieName).add(r);
                }
                //do nothing if rating less than current high
            }
        }
        return lowestRaterMap;
    } 
    
    //  P R I N T   H I G H   O R   L O W   M A P  
    public static void printHighLowRatersMaps(Map<String, List<Rating>> highOrLowMap, Boolean trueForHigh){
        boolean high = trueForHigh;
        String raterString;
        String titlePrintString;
        if(high){
            raterString = "Highest Rater : ";
        } 
        else {
            raterString = "Lowest Rater  : ";
        }
        if(high){
            titlePrintString = " - - - - -   H I G H E S T   R A T E R S   F O R   E A C H   M O V I E   - - - - - ";
        }
        else {
            titlePrintString = " - - - - -   L O W E S T   R A T E R S   F O R   E A C H   M O V I E   - - - - - ";
        }
        System.out.println("");
        System.out.println(titlePrintString);
        System.out.println("");
        for(String title : highOrLowMap.keySet()){
            System.out.println("Movie Name    : " + title);
    
            String output = "";
            for(Rating r : highOrLowMap.get(title)){
                if(output.equals("")){
                    output = r.getRaterName();
                } else {
                    output = output + ", " + r.getRaterName();
                }
            }
            System.out.println(raterString + output);
            System.out.println("");
        }
    }

    //  R A T E R   A V E R A G E
    public static Map<String, Double> raterAverage(List<Rating> ratingsList){
        Map<String, List<Integer>> allRatingsMap = new HashMap<String, List<Integer>>();
        Map<String, Double> raterAverageMap = new HashMap<>();

        //Populate AllRatingsMap
        for (Rating r :ratingsList){
            String raterName = r.getRaterName();
            if (!allRatingsMap.containsKey(raterName)) {
                allRatingsMap.put(raterName, new ArrayList<Integer>());
            }
            //Populate raterAverageMap with rater names
            allRatingsMap.get(raterName).add(r.getMovieRating());
        }

        //calculate average and add to averages map
        for (String rater : allRatingsMap.keySet()){
            List<Integer> movieRatingsList = allRatingsMap.get(rater);
            Double totalRating = 0.0;
            int numOfRatings = 0;
            for(int rating : movieRatingsList){
                totalRating += rating;
                numOfRatings++;
            }
            Double avgRating = totalRating / numOfRatings;
            raterAverageMap.put(rater, avgRating);
        }
        return raterAverageMap;        
    }

    //  H E L P E R   - >   A D D   V A L U E S   T O   A V E R A G E S   L I S T   (used in print highest / lowest raters method)
    public static List<Double> addAveragesToList(Map<String, Double> raterAverageMap){
        List<Double> averagesList = new ArrayList<>();
        for (Double rating : raterAverageMap.values()){
            averagesList.add(rating);
        }
        return averagesList;
    }

    //  P R I N T   H I G H E S T  /  L O W E S T   R A T E R S
    public static void printHighestOrLowestRaters(Map<String, Double> raterAverageMap, boolean TrueForHigh){
        List<Double> averagesList = addAveragesToList(raterAverageMap);
        boolean high = TrueForHigh;
        String titleString;
        if(high){  
            titleString = " - - - - -   H I G H E S T   1 0   R A T E R S   - - - - - ";
            Collections.sort(averagesList, Collections.reverseOrder());    
        }
        else{
            titleString = " - - - - -   L O W E S T   1 0   R A T E R S   - - - - - ";
            Collections.sort(averagesList);
        }
        System.out.println("");
        System.out.println(titleString);
        System.out.println("");
        
        for(int i = 0; i < 10; i++){
            Double avgRating = averagesList.get(i);
            for(String rater : raterAverageMap.keySet()){
                if (raterAverageMap.get(rater) == avgRating){
                    System.out.println("Rater      : " + rater);
                }
            }
            System.out.println("Avg Rating : " + avgRating);
            System.out.println("");
        }
    }

    //  P R I N T   A L L   R A T I N G S
    public static void printAllRatings(List<Rating> ratingsList){
        System.out.println("");
        System.out.println(" - - - - -  P R I N T   A L L   R A T I N G S  - - - - - ");
        System.out.println("");

        for (Rating r : ratingsList) {
            System.out.println(r);
        }
    }
}