/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package u0.movieratings.scottgriffin;
import java.io.IOException;
import java.util.*;

public class App {
        // Map<String, Integer> averageRatings; 
        // Map<String, String> highestRater;
        // Map<String, Integer> topTenRaters;


    public static void main(String[] args) throws IOException {
        RatingReader ratingReader = new RatingReader("move-ratings-test.csv");

        List<Rating> list = ratingReader.getAllRatings();
        averageRating(list);

        //PRINT LIST to confirm working
        // for (Rating r : list) {
        //     System.out.println(r);
        // }






    }  // E N D   O F   M A I N 

   public static void averageRating(List<Rating> list){
        Map<String, List<Integer>> averageRatings = new HashMap<String, List<Integer>>();

        //Populate Map
        for (Rating r :list){
            String movieName = r.getMovieName();
            if (!averageRatings.containsKey(movieName)) {
                averageRatings.put(r.getMovieName(), new ArrayList<Integer>());
            }
            averageRatings.get(r.getMovieName()).add(r.getMovieRating());
        }


            //PRINT MAP (WITHIN METHOD)
            for(String title : averageRatings.keySet()){
                System.out.println(title);
                int numOfRatings = averageRatings.get(title).size();
                int totalRating = 0;

                for (int i : averageRatings.get(title)){
                    totalRating += i;
                }
                double avgRating = totalRating / numOfRatings;
                System.out.println(avgRating);
            }



        }



   }
   



